### ISSUE TITLE
Is this normal? 

### ISSUE THREAD

**Issue by TheTechRobo** [TheJaredWilcurt/karngdarbo#2]
npmLast login: Sun Jul 21 09:35:40 on ttys000
Anfunfuns-MacBook-Air:~ computer$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/computer/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/computer/package.json'
npm WARN computer No description
npm WARN computer No repository field.
npm WARN computer No README data
npm WARN computer No license field.

up to date in 3.566s
found 0 vulnerabilities

Anfunfuns-MacBook-Air:~ computer$ cd Downloads
Anfunfuns-MacBook-Air:Downloads computer$ cd karngdarbo-master
-bash: cd: karngdarbo-master: No such file or directory
Anfunfuns-MacBook-Air:Downloads computer$ cd karngdarbo
-bash: cd: karngdarbo: No such file or directory
Anfunfuns-MacBook-Air:Downloads computer$ karngdarbo
-bash: karngdarbo: command not found
Anfunfuns-MacBook-Air:Downloads computer$ cd karngdarbo-master
-bash: cd: karngdarbo-master: No such file or directory
Anfunfuns-MacBook-Air:Downloads computer$ cd karngdarbo-master
Anfunfuns-MacBook-Air:karngdarbo-master computer$ npm install
 n⸨ ░░░░░░░░░░░░░░░░░⸩ ⠼ fetchMetadata: sill pacote range manifest for http-sign  ⸨ ░░░░░░░░░░░░░░░░░⸩ ⠦ fetchMetadata: sill pacote range manifest for strip-ansnpm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

> fsevents@1.2.9 install /Users/computer/Downloads/karngdarbo-master/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error getaddrinfo ENOTFOUND fsevents-binaries.s3-us-west-2.amazonaws.com fsevents-binaries.s3-us-west-2.amazonaws.com:443 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:197:21)
gyp ERR! stack     at Request.emit (events.js:198:13)
gyp ERR! stack     at Request.onRequestError (/usr/local/lib/node_modules/npm/node_modules/request/request.js:881:8)
gyp ERR! stack     at ClientRequest.emit (events.js:198:13)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:392:9)
gyp ERR! stack     at TLSSocket.emit (events.js:198:13)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:91:8)
gyp ERR! stack     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/computer/Downloads/karngdarbo-master/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/computer/Downloads/karngdarbo-master/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/computer/Downloads/karngdarbo-master/node_modules/fsevents
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/computer/Downloads/karngdarbo-master/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/computer/Downloads/karngdarbo-master/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/computer/Downloads/karngdarbo-master/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 11.4.2
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/computer/Downloads/karngdarbo-master/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/computer/Downloads/karngdarbo-master/node_modules/fsevents
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/computer/Downloads/karngdarbo-master/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/computer/Downloads/karngdarbo-master/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> yorkie@2.0.0 install /Users/computer/Downloads/karngdarbo-master/node_modules/yorkie
> node bin/install.js

setting up Git hooks
can't find .git directory, skipping Git hooks installation

> node-sass@4.12.0 install /Users/computer/Downloads/karngdarbo-master/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-64_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/computer/Downloads/karngdarbo-master/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Caching binary to /Users/computer/.npm/node-sass/4.12.0/darwin-x64-64_binding.node

> core-js@2.6.9 postinstall /Users/computer/Downloads/karngdarbo-master/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> node-sass@4.12.0 postinstall /Users/computer/Downloads/karngdarbo-master/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/computer/Downloads/karngdarbo-master/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine

> nw@0.39.3-sdk postinstall /Users/computer/Downloads/karngdarbo-master/node_modules/nw
> node scripts/install.js

getaddrinfo ENOTFOUND dl.nwjs.io dl.nwjs.io:443
npm WARN karngdarbo@0.1.0 No repository field.
npm WARN karngdarbo@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nw@0.39.3-sdk postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.39.3-sdk postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/computer/.npm/_logs/2019-07-21T16_17_42_067Z-debug.log
Anfunfuns-MacBook-Air:karngdarbo-master computer$ clear

Anfunfuns-MacBook-Air:karngdarbo-master computer$ npm install

> fsevents@1.2.9 install /Users/computer/Downloads/karngdarbo-master/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/computer/Downloads/karngdarbo-master/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> nw@0.39.3-sdk postinstall /Users/computer/Downloads/karngdarbo-master/node_modules/nw
> node scripts/install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN karngdarbo@0.1.0 No repository field.
npm WARN karngdarbo@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

added 142 packages from 61 contributors in 983.612s
Anfunfuns-MacBook-Air:karngdarbo-master computer$ npm start

> karngdarbo@0.1.0 start /Users/computer/Downloads/karngdarbo-master
> concurrently "vue-cli-service serve --port=8964" "nw ."

[1] nw . exited with code 0
[0]  INFO  Starting development server...
 98% after emitting CopyPlugin DONE  Compiled successfully in 106648ms12:54:22 PM 
[0] 
    
[0]   App running at:
[0]   - Local:   http://localhost:8964/ 
[0]   - Network: http://192.168.2.60:8964/
[0] 
[0]   Note that the development build is not optimized.
[0]   To create a production build, run npm run build.
[0] 
^Cevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn pgrep ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! karngdarbo@0.1.0 start: `concurrently "vue-cli-service serve --port=8964" "nw ."`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the karngdarbo@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/computer/.npm/_logs/2019-07-21T17_12_09_633Z-debug.log
Anfunfuns-MacBook-Air:karngdarbo-master computer$ 

NOTE: the first error is because my Mac went to sleep
At the end, I pressed Ctrl-C
When it was running, I went to the localhost server provided and there was a blank creen with the only thing showing is the tap facivon and a title in the tab bar.

**Comment by TheJaredWilcurt** [comment]
I would recommend deleting the `package-lock.json` and `node_modules` folder and doing a fresh `npm install`. Some of that is normal, but some things are not. Make sure you computer doesn't go to sleep this time.

**Comment by TheTechRobo** [comment]
okay, thanks, trying that :)
